Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 6
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	32	featureExtract
	33

[Tue Jul 28 19:35:02 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-06_space-T1w_desc-coarse_features.hkl
    jobid: 6
    wildcards: afid_num=06

[Tue Jul 28 19:35:02 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-13_space-T1w_desc-coarse_features.hkl
    jobid: 13
    wildcards: afid_num=13

[Tue Jul 28 19:35:02 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-21_space-T1w_desc-coarse_features.hkl
    jobid: 21
    wildcards: afid_num=21

[Tue Jul 28 19:35:02 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-28_space-T1w_desc-coarse_features.hkl
    jobid: 28
    wildcards: afid_num=28

[Tue Jul 28 19:35:02 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-07_space-T1w_desc-coarse_features.hkl
    jobid: 7
    wildcards: afid_num=07

[Tue Jul 28 19:35:02 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-14_space-T1w_desc-coarse_features.hkl
    jobid: 14
    wildcards: afid_num=14

[Tue Jul 28 19:35:21 2020]
Error in rule featureExtract:
    jobid: 13
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-13_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 21 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmpp2l6bucq.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 21, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 19:35:21 2020]
Error in rule featureExtract:
    jobid: 21
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-21_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 21 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmpyxp583oz.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 21, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 19:35:22 2020]
Error in rule featureExtract:
    jobid: 28
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-28_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 21 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmp7ld3v62h.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 21, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 19:35:22 2020]
Error in rule featureExtract:
    jobid: 14
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-14_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 21 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmpt96yybfk.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 21, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 19:35:22 2020]
Error in rule featureExtract:
    jobid: 6
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-06_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 21 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmp2c_f5413.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 21, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 19:35:22 2020]
Error in rule featureExtract:
    jobid: 7
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-07_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 21 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmp4rqp_ejh.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 21, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/log/2020-07-28T193501.903584.snakemake.log
