Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 6
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	32	featureExtract
	33

[Tue Jul 28 19:53:40 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-02_space-T1w_desc-coarse_features.hkl
    jobid: 2
    wildcards: afid_num=02

[Tue Jul 28 19:53:40 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-10_space-T1w_desc-coarse_features.hkl
    jobid: 10
    wildcards: afid_num=10

[Tue Jul 28 19:53:40 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-17_space-T1w_desc-coarse_features.hkl
    jobid: 17
    wildcards: afid_num=17

[Tue Jul 28 19:53:40 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-25_space-T1w_desc-coarse_features.hkl
    jobid: 25
    wildcards: afid_num=25

[Tue Jul 28 19:53:40 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-32_space-T1w_desc-coarse_features.hkl
    jobid: 32
    wildcards: afid_num=32


[Tue Jul 28 19:53:40 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-03_space-T1w_desc-coarse_features.hkl
    jobid: 3
    wildcards: afid_num=03

[Tue Jul 28 19:53:40 2020]
Error in rule featureExtract:
    jobid: 25
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-25_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmpk9n08ini.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 19:53:40 2020]
Error in rule featureExtract:
    jobid: 2
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-02_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmp52enaisa.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 19:53:40 2020]
Error in rule featureExtract:
    jobid: 10
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-10_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmpp7hj2ihr.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 19:53:40 2020]
Error in rule featureExtract:
    jobid: 17
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-17_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmpssgizgyl.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 19:53:40 2020]
Error in rule featureExtract:
    jobid: 32
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-32_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmphpypv6ej.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 19:53:40 2020]
Error in rule featureExtract:
    jobid: 3
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-03_space-T1w_desc-coarse_features.hkl

RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmp1by24950.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/log/2020-07-28T195339.552948.snakemake.log
