Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 6
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	96	featureExtract
	96	modelTrain
	193

[Tue Jul 28 21:39:03 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-02_space-T1w_desc-medium_features.hkl
    jobid: 5
    wildcards: afid_num=02, train_level=medium

[Tue Jul 28 21:39:03 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-12_space-T1w_desc-medium_features.hkl
    jobid: 35
    wildcards: afid_num=12, train_level=medium

[Tue Jul 28 21:39:03 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-17_space-T1w_desc-medium_features.hkl
    jobid: 50
    wildcards: afid_num=17, train_level=medium

[Tue Jul 28 21:39:03 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-22_space-T1w_desc-medium_features.hkl
    jobid: 65
    wildcards: afid_num=22, train_level=medium

[Tue Jul 28 21:39:03 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-32_space-T1w_desc-medium_features.hkl
    jobid: 95
    wildcards: afid_num=32, train_level=medium

[Tue Jul 28 21:39:03 2020]
rule featureExtract:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-02_space-T1w_desc-fine_features.hkl
    jobid: 6
    wildcards: afid_num=02, train_level=fine

[Tue Jul 28 21:39:03 2020]
[Tue Jul 28 21:39:03 2020]
Error in rule featureExtract:
Error in rule featureExtract:
    jobid: 95
    jobid: 5
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-32_space-T1w_desc-medium_features.hkl
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-02_space-T1w_desc-medium_features.hkl


RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmp5j2gvr9d.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmpex_h2og7.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 21:39:03 2020]
Error in rule featureExtract:
    jobid: 35
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-12_space-T1w_desc-medium_features.hkl

RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmpah7mxac8.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 21:39:03 2020]
Error in rule featureExtract:
    jobid: 6
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-02_space-T1w_desc-fine_features.hkl

RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmpsnypguph.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 21:39:03 2020]
Error in rule featureExtract:
    jobid: 65
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-22_space-T1w_desc-medium_features.hkl

RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmp5r9lbtzq.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Tue Jul 28 21:39:03 2020]
Error in rule featureExtract:
    jobid: 50
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-17_space-T1w_desc-medium_features.hkl

RuleException:
CalledProcessError in line 20 of /home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/scripts/tmpke1i4qdn.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/modeling/workflow/rules/modelTraining.smk", line 20, in __rule_featureExtract
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/greydon/Documents/GitHub/Auto-afids/modeling/.snakemake/log/2020-07-28T213902.711437.snakemake.log
